Repository eclipse-edc/Technology-Gcp, pull requests merged in 2023-10, with the labels that each got.

#55 fix: compilation errors, typo in GCS provisioner, IAM client delete account
  DEPENDENCIES
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/edc/gcp/iam/IamServiceImpl.java
  extensions/common/gcp/gcp-core/src/test/java/org/eclipse/edc/gcp/iam/IamServiceImplTest.java
  extensions/control-plane/provision/provision-gcs/src/main/java/org/eclipse/edc/connector/provision/gcp/GcsProvisioner.java
  extensions/data-plane/data-plane-google-storage/src/main/java/org/eclipse/edc/connector/dataplane/gcp/storage/GcsDataSource.java
  settings.gradle.kts
Labels: bug

#57 feat: GCP common extension
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/edc/gcp/common/GcpConfiguration.java
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/edc/gcp/common/GcpExtension.java
  extensions/common/gcp/gcp-core/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/common/vault/vault-gcp/build.gradle.kts
  extensions/common/vault/vault-gcp/src/main/java/org/eclipse/edc/vault/gcp/GcpSecretManagerVaultExtension.java
  extensions/common/vault/vault-gcp/src/test/java/org/eclipse/edc/vault/gcp/GcpSecretManagerVaultExtensionTest.java
  extensions/control-plane/provision/provision-gcs/src/main/java/org/eclipse/edc/connector/provision/gcp/GcsProvisionExtension.java
  extensions/data-plane/data-plane-google-storage/src/main/java/org/eclipse/edc/connector/dataplane/gcp/storage/GcsDataSink.java
Labels: bug, feature_request

#60 feat: core gcs enhancement
  DEPENDENCIES
  extensions/common/gcp/gcp-core/build.gradle.kts
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/edc/gcp/common/GcpCredentials.java
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/edc/gcp/common/GcpServiceAccountCredentials.java
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/edc/gcp/storage/GcsStoreSchema.java
  extensions/common/gcp/gcp-core/src/test/java/org/eclipse/edc/gcp/common/GcpCredentialsTest.java
  extensions/common/vault/vault-gcp/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
Labels: enhancement
