Repository eclipse-edc/Technology-Gcp, pull requests merged in 2024-08, with the labels that each got.

#209 fix(ci): set version before tests, publishing
  .github/workflows/publish.yaml
  .github/workflows/release-tech-gcp.yml
  .github/workflows/verify.yaml
  DEPENDENCIES
Labels: bug

#214 ci: launch test workflow also on release and bugfix branches
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependency-check.yml
  .github/workflows/nightly.yaml
  .github/workflows/verify.yaml
  DEPENDENCIES
  gradle/libs.versions.toml
  system-tests/runtimes/gcp-bigquery-transfer-consumer/build.gradle.kts
  system-tests/runtimes/gcp-bigquery-transfer-provider/build.gradle.kts
Labels: enhancement

#219 build(deps): bump gradle wrapper to 8.10
  .github/workflows/verify.yaml
  DEPENDENCIES
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies
