Repository eclipse-edc/Technology-Gcp, pull requests merged in 2024-01, with the labels that each got.

#101 build: bump gradle-wrapper to 8.5
  DEPENDENCIES
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#105 fix: compile errors after EDC token refactor
  DEPENDENCIES
  extensions/common/vault/vault-gcp/src/main/java/org/eclipse/edc/vault/gcp/GcpSecretManagerVaultExtension.java
  extensions/common/vault/vault-gcp/src/test/java/org/eclipse/edc/vault/gcp/GcpSecretManagerVaultExtensionTest.java
Labels: bug

#106 build: make trigger_snapshot workflow manually triggerable
  .github/ISSUE_TEMPLATE/adoption_request.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/bump-version/action.yml
  .github/actions/run-tests/action.yml
  .github/actions/setup-build/action.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/release-tech-gcp.yml
  .github/workflows/trigger_snapshot.yml
  .github/workflows/verify.yaml
Labels: enhancement

#111 feat: GCS provisioner using ADC or existing service account for access tokens
  DEPENDENCIES
  extensions/common/gcp/gcp-core/build.gradle.kts
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/edc/gcp/common/GcpConfiguration.java
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/edc/gcp/iam/AccessTokenProvider.java
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/edc/gcp/iam/IamService.java
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/edc/gcp/iam/IamServiceImpl.java
  extensions/common/gcp/gcp-core/src/test/java/org/eclipse/edc/gcp/iam/IamServiceImplTest.java
  extensions/control-plane/provision/provision-gcs/src/main/java/org/eclipse/edc/connector/provision/gcp/GcsConsumerResourceDefinitionGenerator.java
  extensions/control-plane/provision/provision-gcs/src/main/java/org/eclipse/edc/connector/provision/gcp/GcsProvisionExtension.java
  extensions/control-plane/provision/provision-gcs/src/main/java/org/eclipse/edc/connector/provision/gcp/GcsProvisioner.java
  extensions/control-plane/provision/provision-gcs/src/main/java/org/eclipse/edc/connector/provision/gcp/GcsResourceDefinition.java
  extensions/control-plane/provision/provision-gcs/src/test/java/org/eclipse/edc/connector/provision/gcp/GcsProvisionerTest.java
  gradle/libs.versions.toml
Labels: enhancement, feature_request

#121 build: use GCP BOM version catalog
  DEPENDENCIES
  extensions/common/gcp/gcp-core/build.gradle.kts
  extensions/common/vault/vault-gcp/build.gradle.kts
  extensions/control-plane/provision/provision-gcs/build.gradle.kts
  extensions/data-plane/data-plane-google-storage/build.gradle.kts
  gradle/libs.versions.toml
Labels: dependencies
